1. Create two random 3x3 matrices (A and B)
Perform element-wise addition, subtraction, multiplication, and division on these matrices.
Compute the dot product of A and the transpose of B.

In [ ]:
import numpy as np
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

print("array1: \n", A)
print("array2: \n", B, "\n\n")

print("add(element-wise): \n", A+B)
print("sub(element-wise): \n", A-B)
print("mul(element-wise): \n", A*B)
print("div(element-wise): \n", A/B, "\n\n")

print("A . trnaspose(B): \n", np.dot(A, B.transpose()))


array1: 
 [[0.27358941 0.99959572 0.43439189]
 [0.53058868 0.59122457 0.66121303]
 [0.62496548 0.31253201 0.82458035]]
array2: 
 [[0.1835784  0.69667302 0.27880803]
 [0.94750075 0.84032115 0.86794213]
 [0.18592944 0.33898509 0.59254542]] 


add(element-wise): 
 [[0.4571678  1.69626874 0.71319992]
 [1.47808943 1.43154572 1.52915516]
 [0.81089493 0.6515171  1.41712577]]
sub(element-wise): 
 [[ 0.09001101  0.30292271  0.15558385]
 [-0.41691208 -0.24909658 -0.20672909]
 [ 0.43903604 -0.02645308  0.23203493]]
mul(element-wise): 
 [[0.0502251  0.69639137 0.12111195]
 [0.50273317 0.49681851 0.57389465]
 [0.11619948 0.10594369 0.48860131]]
div(element-wise): 
 [[1.49031373 1.43481332 1.55803218]
 [0.5599876  0.70356978 0.76181696]
 [3.36130455 0.92196389 1.39159012]] 


A . trnaspose(B): 
 [[0.86772842 1.47623461 0.64711329]
 [0.69364633 1.57344633 0.69086713]
 [0.56236241 1.57047055 0.71074449]]


2. Generate a NumPy array with integers from 0 to 20.
Extract all even numbers using array slicing.
Replace all odd numbers with -1.

In [ ]:
import numpy as np
array = np.arange(0, 21)
eve = array[0::2]
array[1::2] = [-1]

print("even: ", eve)
print("after replacing:", array)


even:  [ 0  2  4  6  8 10 12 14 16 18 20]
after replacing: [ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20]


3. Create a random 1D array with 100 elements.
Calculate the mean, median, and standard deviation of the array.
Identify the index of the maximum and minimum values in the array.

In [ ]:
import numpy as np
arr = np.random.rand(100)

mean = np.mean(arr)
median = np.median(arr)
SD = np.std(arr)

max = np.argmax(arr)
min = np.argmin(arr)

print("mean: ", mean)
print("median: ", median)
print("std deviation: ", SD)
print("max index: ", max)
print("min index: ", min)


mean:  0.4911200535103073
median:  0.5159493662639956
std deviation:  0.2792750463220658
max index:  56
min index:  28
